language: node_js
dist: bionic
notifications:
  email:
    recipients:
    - middleware@hexonet.net
    on_success: never
    on_failure: always
node_js:
  - 'lts/*'
before_install:
- npm prune
install:
- travis_retry npm i
script:
- npm run lint
- npx semantic-release
